service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  buckets:
    originalImageBucket: ${env:DOMAIN_NAME}-original-images 
    resizedImageBucket: ${env:DOMAIN_NAME}-resized-images 
  jest:
    collectCoverage: true

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ORIGINAL_IMAGE_BUCKET: ${self:custom.buckets.originalImageBucket}
    RESIZED_IMAGE_BUCKET: ${self:custom.buckets.resizedImageBucket}

functions:
  storeOriginal:
    handler: src/handler.storeOriginal
    events:
      - http:
          method: post
          path: original-images
  getResized:
    handler: src/handler.getResized
    events:
      - http:
          method: get
          path: resized-images
