service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ORIGINAL_IMAGE_BUCKET: kf-original-image-dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: hello
